services:
  - type: web
    name: api-gateway
    runtime: docker
    plan: free
    rootDir: apps/api-gatway
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: AUTH_HOSTPORT
        fromService:
          name: auth-service
          type: pserv
          property: hostport
      - key: NODE_ENV
        value: production

  - type: pserv
    name: auth-service
    runtime: docker
    plan: free
    rootDir: apps/auth-service
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
